%% Erlang 17 moves various types into module namespaces
%% Use the ifdef to be backward compatible
-ifdef(namespaced_types).
-type edns_set() :: sets:set().
-type edns_dict() :: dict:dict().
-type edns_gb_tree() :: gb_trees:gb_tree().
-else.
-type edns_set() :: set().
-type edns_dict() :: dict().
-type edns_gb_tree() :: gb_tree().
-endif.

-record(partial_zone, {
          name :: dns:dname(),
          allow_notify = [] :: [inet:ip_address()],
          allow_transfer = [] :: [inet:ip_address()],
          allow_update = [] :: [inet:ip_address()],
          also_notify = [] :: [inet:ip_address()],
          notify_source = {127,0,0,1} :: inet:ip_address(),
          records = [] :: [dns:rr()],
          sha = <<>> :: binary()
         }).

-record(zone, {
          name :: dns:dname(),
          allow_notify :: [inet:ip_address()],
          allow_transfer :: [inet:ip_address()],
          allow_update :: [inet:ip_address()],
          also_notify :: [inet:ip_address()],
          notify_source :: inet:ip_address(),
          version :: binary(),
          authority = [] :: [dns:rr()],
          record_count = 0 :: non_neg_integer(),
          records = [] :: [dns:rr()],
          records_by_name :: [dns:rr()],
          records_by_type :: [dns:rr()]
         }).

-record(authorities, {
          owner_name,
          ttl,
          class,
          name_server,
          email_addr,
          serial_num,
          refresh,
          retry,
          expiry,
          nxdomain
         }).

-record(geolocation, {
          name :: binary(),
          continent :: atom(),
          country :: undefined | binary(),
          regions :: undefined | list(binary())}).

-define(ADMIN_PORT, 9000).
-define(DNS_LISTEN_PORT, 8053).
-define(LOCAL_HOSTS, [{127, 0, 0, 1}, {0, 0, 0, 0, 0, 0, 0, 1}]).

-define(COUNTRY_CODES,
        [{<<"A1">>,undefined},
        {<<"A2">>,undefined},
        {<<"AD">>,<<"EU">>},
        {<<"AE">>,<<"AS">>},
        {<<"AF">>,<<"AS">>},
        {<<"AG">>,<<"NA">>},
        {<<"AI">>,<<"NA">>},
        {<<"AL">>,<<"EU">>},
        {<<"AM">>,<<"AS">>},
        {<<"AN">>,<<"NA">>},
        {<<"AO">>,<<"AF">>},
        {<<"AP">>,<<"AS">>},
        {<<"AQ">>,<<"AN">>},
        {<<"AR">>,<<"SA">>},
        {<<"AS">>,<<"OC">>},
        {<<"AT">>,<<"EU">>},
        {<<"AU">>,<<"OC">>},
        {<<"AW">>,<<"NA">>},
        {<<"AX">>,<<"EU">>},
        {<<"AZ">>,<<"AS">>},
        {<<"BA">>,<<"EU">>},
        {<<"BB">>,<<"NA">>},
        {<<"BD">>,<<"AS">>},
        {<<"BE">>,<<"EU">>},
        {<<"BF">>,<<"AF">>},
        {<<"BG">>,<<"EU">>},
        {<<"BH">>,<<"AS">>},
        {<<"BI">>,<<"AF">>},
        {<<"BJ">>,<<"AF">>},
        {<<"BL">>,<<"NA">>},
        {<<"BM">>,<<"NA">>},
        {<<"BN">>,<<"AS">>},
        {<<"BO">>,<<"SA">>},
        {<<"BR">>,<<"SA">>},
        {<<"BS">>,<<"NA">>},
        {<<"BT">>,<<"AS">>},
        {<<"BV">>,<<"AN">>},
        {<<"BW">>,<<"AF">>},
        {<<"BY">>,<<"EU">>},
        {<<"BZ">>,<<"NA">>},
        {<<"CA">>,<<"NA">>},
        {<<"CC">>,<<"AS">>},
        {<<"CD">>,<<"AF">>},
        {<<"CF">>,<<"AF">>},
        {<<"CG">>,<<"AF">>},
        {<<"CI">>,<<"AF">>},
        {<<"CK">>,<<"OC">>},
        {<<"CL">>,<<"SA">>},
        {<<"CM">>,<<"AF">>},
        {<<"CN">>,<<"AS">>},
        {<<"CO">>,<<"SA">>},
        {<<"CR">>,<<"NA">>},
        {<<"CU">>,<<"NA">>},
        {<<"CV">>,<<"AF">>},
        {<<"CX">>,<<"AS">>},
        {<<"CY">>,<<"AS">>},
        {<<"CZ">>,<<"EU">>},
        {<<"DE">>,<<"EU">>},
        {<<"DJ">>,<<"AF">>},
        {<<"DK">>,<<"EU">>},
        {<<"DM">>,<<"NA">>},
        {<<"DO">>,<<"NA">>},
        {<<"DZ">>,<<"AF">>},
        {<<"EC">>,<<"SA">>},
        {<<"EE">>,<<"EU">>},
        {<<"EG">>,<<"AF">>},
        {<<"EH">>,<<"AF">>},
        {<<"ER">>,<<"AF">>},
        {<<"ES">>,<<"EU">>},
        {<<"ET">>,<<"AF">>},
        {<<"EU">>,<<"EU">>},
        {<<"FI">>,<<"EU">>},
        {<<"FJ">>,<<"OC">>},
        {<<"FK">>,<<"SA">>},
        {<<"FM">>,<<"OC">>},
        {<<"FO">>,<<"EU">>},
        {<<"FR">>,<<"EU">>},
        {<<"FX">>,<<"EU">>},
        {<<"GA">>,<<"AF">>},
        {<<"GB">>,<<"EU">>},
        {<<"GD">>,<<"NA">>},
        {<<"GE">>,<<"AS">>},
        {<<"GF">>,<<"SA">>},
        {<<"GG">>,<<"EU">>},
        {<<"GH">>,<<"AF">>},
        {<<"GI">>,<<"EU">>},
        {<<"GL">>,<<"NA">>},
        {<<"GM">>,<<"AF">>},
        {<<"GN">>,<<"AF">>},
        {<<"GP">>,<<"NA">>},
        {<<"GQ">>,<<"AF">>},
        {<<"GR">>,<<"EU">>},
        {<<"GS">>,<<"AN">>},
        {<<"GT">>,<<"NA">>},
        {<<"GU">>,<<"OC">>},
        {<<"GW">>,<<"AF">>},
        {<<"GY">>,<<"SA">>},
        {<<"HK">>,<<"AS">>},
        {<<"HM">>,<<"AN">>},
        {<<"HN">>,<<"NA">>},
        {<<"HR">>,<<"EU">>},
        {<<"HT">>,<<"NA">>},
        {<<"HU">>,<<"EU">>},
        {<<"ID">>,<<"AS">>},
        {<<"IE">>,<<"EU">>},
        {<<"IL">>,<<"AS">>},
        {<<"IM">>,<<"EU">>},
        {<<"IN">>,<<"AS">>},
        {<<"IO">>,<<"AS">>},
        {<<"IQ">>,<<"AS">>},
        {<<"IR">>,<<"AS">>},
        {<<"IS">>,<<"EU">>},
        {<<"IT">>,<<"EU">>},
        {<<"JE">>,<<"EU">>},
        {<<"JM">>,<<"NA">>},
        {<<"JO">>,<<"AS">>},
        {<<"JP">>,<<"AS">>},
        {<<"KE">>,<<"AF">>},
        {<<"KG">>,<<"AS">>},
        {<<"KH">>,<<"AS">>},
        {<<"KI">>,<<"OC">>},
        {<<"KM">>,<<"AF">>},
        {<<"KN">>,<<"NA">>},
        {<<"KP">>,<<"AS">>},
        {<<"KR">>,<<"AS">>},
        {<<"KW">>,<<"AS">>},
        {<<"KY">>,<<"NA">>},
        {<<"KZ">>,<<"AS">>},
        {<<"LA">>,<<"AS">>},
        {<<"LB">>,<<"AS">>},
        {<<"LC">>,<<"NA">>},
        {<<"LI">>,<<"EU">>},
        {<<"LK">>,<<"AS">>},
        {<<"LR">>,<<"AF">>},
        {<<"LS">>,<<"AF">>},
        {<<"LT">>,<<"EU">>},
        {<<"LU">>,<<"EU">>},
        {<<"LV">>,<<"EU">>},
        {<<"LY">>,<<"AF">>},
        {<<"MA">>,<<"AF">>},
        {<<"MC">>,<<"EU">>},
        {<<"MD">>,<<"EU">>},
        {<<"ME">>,<<"EU">>},
        {<<"MF">>,<<"NA">>},
        {<<"MG">>,<<"AF">>},
        {<<"MH">>,<<"OC">>},
        {<<"MK">>,<<"EU">>},
        {<<"ML">>,<<"AF">>},
        {<<"MM">>,<<"AS">>},
        {<<"MN">>,<<"AS">>},
        {<<"MO">>,<<"AS">>},
        {<<"MP">>,<<"OC">>},
        {<<"MQ">>,<<"NA">>},
        {<<"MR">>,<<"AF">>},
        {<<"MS">>,<<"NA">>},
        {<<"MT">>,<<"EU">>},
        {<<"MU">>,<<"AF">>},
        {<<"MV">>,<<"AS">>},
        {<<"MW">>,<<"AF">>},
        {<<"MX">>,<<"NA">>},
        {<<"MY">>,<<"AS">>},
        {<<"MZ">>,<<"AF">>},
        {<<"NA">>,<<"AF">>},
        {<<"NC">>,<<"OC">>},
        {<<"NE">>,<<"AF">>},
        {<<"NF">>,<<"OC">>},
        {<<"NG">>,<<"AF">>},
        {<<"NI">>,<<"NA">>},
        {<<"NL">>,<<"EU">>},
        {<<"NO">>,<<"EU">>},
        {<<"NP">>,<<"AS">>},
        {<<"NR">>,<<"OC">>},
        {<<"NU">>,<<"OC">>},
        {<<"NZ">>,<<"OC">>},
        {<<"O1">>,undefined},
        {<<"OM">>,<<"AS">>},
        {<<"PA">>,<<"NA">>},
        {<<"PE">>,<<"SA">>},
        {<<"PF">>,<<"OC">>},
        {<<"PG">>,<<"OC">>},
        {<<"PH">>,<<"AS">>},
        {<<"PK">>,<<"AS">>},
        {<<"PL">>,<<"EU">>},
        {<<"PM">>,<<"NA">>},
        {<<"PN">>,<<"OC">>},
        {<<"PR">>,<<"NA">>},
        {<<"PS">>,<<"AS">>},
        {<<"PT">>,<<"EU">>},
        {<<"PW">>,<<"OC">>},
        {<<"PY">>,<<"SA">>},
        {<<"QA">>,<<"AS">>},
        {<<"RE">>,<<"AF">>},
        {<<"RO">>,<<"EU">>},
        {<<"RS">>,<<"EU">>},
        {<<"RU">>,<<"EU">>},
        {<<"RW">>,<<"AF">>},
        {<<"SA">>,<<"AS">>},
        {<<"SB">>,<<"OC">>},
        {<<"SC">>,<<"AF">>},
        {<<"SD">>,<<"AF">>},
        {<<"SE">>,<<"EU">>},
        {<<"SG">>,<<"AS">>},
        {<<"SH">>,<<"AF">>},
        {<<"SI">>,<<"EU">>},
        {<<"SJ">>,<<"EU">>},
        {<<"SK">>,<<"EU">>},
        {<<"SL">>,<<"AF">>},
        {<<"SM">>,<<"EU">>},
        {<<"SN">>,<<"AF">>},
        {<<"SO">>,<<"AF">>},
        {<<"SR">>,<<"SA">>},
        {<<"ST">>,<<"AF">>},
        {<<"SV">>,<<"NA">>},
        {<<"SY">>,<<"AS">>},
        {<<"SZ">>,<<"AF">>},
        {<<"TC">>,<<"NA">>},
        {<<"TD">>,<<"AF">>},
        {<<"TF">>,<<"AN">>},
        {<<"TG">>,<<"AF">>},
        {<<"TH">>,<<"AS">>},
        {<<"TJ">>,<<"AS">>},
        {<<"TK">>,<<"OC">>},
        {<<"TL">>,<<"AS">>},
        {<<"TM">>,<<"AS">>},
        {<<"TN">>,<<"AF">>},
        {<<"TO">>,<<"OC">>},
        {<<"TR">>,<<"EU">>},
        {<<"TT">>,<<"NA">>},
        {<<"TV">>,<<"OC">>},
        {<<"TW">>,<<"AS">>},
        {<<"TZ">>,<<"AF">>},
        {<<"UA">>,<<"EU">>},
        {<<"UG">>,<<"AF">>},
        {<<"UM">>,<<"OC">>},
        {<<"US">>,<<"NA">>},
        {<<"UY">>,<<"SA">>},
        {<<"UZ">>,<<"AS">>},
        {<<"VA">>,<<"EU">>},
        {<<"VC">>,<<"NA">>},
        {<<"VE">>,<<"SA">>},
        {<<"VG">>,<<"NA">>},
        {<<"VI">>,<<"NA">>},
        {<<"VN">>,<<"AS">>},
        {<<"VU">>,<<"OC">>},
        {<<"WF">>,<<"OC">>},
        {<<"WS">>,<<"OC">>},
        {<<"YE">>,<<"AS">>},
        {<<"YT">>,<<"AF">>},
        {<<"ZA">>,<<"AF">>},
        {<<"ZM">>,<<"AF">>},
        {<<"ZW">>,<<"AF">>}]
       ).